---
title: "HW4_RMarkdown"
output: html_document
date: "2022-10-27"
---
##Setting Up Libraries
```{r setup, include=FALSE}
library(sp)
library(sf)
library(fs)
library(tmap)
library(tmaptools)
library(RSQLite)
library(tidyverse)
library(rgdal)
library(readr)
library(dplyr)
library(OpenStreetMap)
library(janitor)
library(terra)
library(raster)
library(ggplot2)
library(here)
library(readr)
library(plotly)
library(countrycode)
```

##Reading in the Data
```{r}

UN_composite_data <- read_csv(here::here("hw4_data", "Composite_Indices.csv")) %>% 
  clean_names()

world_data <- st_read(here("hw4_data", "World_Countries_(Generalized).geojson"))

```

##Filtering and Organising the Data

```{r}
filtered_composite <- UN_composite_data %>% 
  dplyr::select(country, contains("gii"))
  
filtered_composite2010_2019 <- filtered_composite %>% 
  dplyr::select(country, gii_2010, gii_2019) %>% 
  mutate(difference = (filtered_composite$gii_2019)-(filtered_composite$gii_2010))

```

##Joining the Spatial and Nonspatial Data

```{r pressure, echo=FALSE}

giidiff_map <- world_data %>% 
  clean_names() %>% 
  left_join(., filtered_composite2010_2019, by = c("country" = "country"))
```

##Maps

In this simple map, the difference is presented based on the 2019 data minus the 2010 data. Here, the red indicates a greater degree of difference and therefore a greater improvement in gender inequality.

```{r}
qtm(giidiff_map, fill = "difference")
```

